# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

registries:
    github-packages:
        type: npm-registry
        url: 'https://npm.pkg.github.com'
        token: ${{ secrets.DEPENDABOT_GITHUB_PACKAGES }}

updates:
    - package-ecosystem: 'npm' # See documentation for possible values
      directory: '/' # Location of package manifests
      schedule:
          interval: 'weekly'
      groups:
          gatsby:
              patterns:
                  - 'gatsby*'

    - package-ecosystem: 'npm'
      registries:
          - 'github-packages'
      directory: '/site'
      schedule:
          interval: 'monthly'

    # Maintain dependencies for GitHub Actions
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'weekly'
