name: Release

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: '20.x'

      - name: Install node modules and verify build
        run: npm install && npm run build-release

      - name: Lint and test
        run: npm run lint && npm run test

      - name: Publish
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public